# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
image: python:3.6

pages:
  stage: deploy
  script:
    - python3 -m pip install mkdocs mkdocs-material mkdocstrings
    - mkdocs build
  artifacts:
    paths:
      - site
  only:
    - master
