image: python:latest
pages:
  stage: deploy
  only:
    - release-doc
  script:
    - pip install mkdocs-material mkdocstrings mkdocs-jupyter mkdocstrings-python-legacy colour deprecated pyyml ipython
    - PYTHONPATH=src mkdocs build --site-dir public
  artifacts:
    paths:
      - public
